# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/SignUpandloginForms.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Resources
import pymysql as sql
import sys, os
from PyQt5.QtCore import Qt, QRect, QPropertyAnimation, QSequentialAnimationGroup
from win32api import GetSystemMetrics

class Sign_Up_and_Login_Form(object):
        def __init__(self, str_to_check):
                self.maximized = False
                self.MainWindow = QtWidgets.QMainWindow()
                self.connection = sql.connect(host='localhost', user='root', password='', database='tms')
                self.cursor = self.connection.cursor()
                self.setupUi()
                if str_to_check == "Login":
                        self.stackedWidget.setCurrentWidget(self.LoginForPage)
                else:
                        self.stackedWidget.setCurrentWidget(self.SignUpPage)
                self.connect_login_buttons()
                self.connect_signup_buttons()
                self.connect_upper_bar_buttons()
                self.MainWindow.show()

        def setupUi(self):
                self.MainWindow.setObjectName("MainWindow")
                self.MainWindow.resize(782, 567)
                self.centralwidget = QtWidgets.QWidget(self.MainWindow)
                self.MainWindow.setAttribute(Qt.WA_TranslucentBackground)
                self.MainWindow.setWindowFlag(Qt.FramelessWindowHint)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setObjectName("verticalLayout")
                self.widget_7 = QtWidgets.QWidget(self.centralwidget)
                self.widget_7.setStyleSheet("QPushButton{\n"
        "background-color:white;\n"
        "border-radius:15px;\n"
        "padding:10px;\n"
        "}")
                self.widget_7.setObjectName("widget_7")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label_10 = QtWidgets.QLabel(self.widget_7)
                font = QtGui.QFont()
                font.setFamily("Segoe MDL2 Assets")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setText("")
                self.label_10.setTextFormat(QtCore.Qt.AutoText)
                self.label_10.setPixmap(QtGui.QPixmap(":/Icons/Icons/trello.svg"))
                self.label_10.setObjectName("label_10")
                self.horizontalLayout_2.addWidget(self.label_10)
                self.label_12 = QtWidgets.QLabel(self.widget_7)
                font = QtGui.QFont()
                font.setFamily("Segoe MDL2 Assets")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_12.setFont(font)
                self.label_12.setObjectName("label_12")
                self.horizontalLayout_2.addWidget(self.label_12)
                spacerItem = QtWidgets.QSpacerItem(583, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem)
                self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
                self.pushButton_5.setStyleSheet(":hover{\n"
        "background-color: yellow;\n"
        "color: white;\n"
        "font-weight: bold;\n"
        "}")
                self.pushButton_5.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton_5.setIcon(icon)
                self.pushButton_5.setObjectName("pushButton_5")
                self.horizontalLayout_2.addWidget(self.pushButton_5)
                self.pushButton_7 = QtWidgets.QPushButton(self.widget_7)
                self.pushButton_7.setStyleSheet(":hover{\n"
        "background-color: red;\n"
        "color: white;\n"
        "font-weight: bold;\n"
        "}")
                self.pushButton_7.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton_7.setIcon(icon1)
                self.pushButton_7.setObjectName("pushButton_7")
                self.horizontalLayout_2.addWidget(self.pushButton_7)
                self.verticalLayout.addWidget(self.widget_7)
                self.TitleLable = QtWidgets.QLabel(self.centralwidget)
                font = QtGui.QFont()
                font.setFamily("MS PGothic")
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.TitleLable.setFont(font)
                self.TitleLable.setObjectName("TitleLable")
                self.verticalLayout.addWidget(self.TitleLable, 0, QtCore.Qt.AlignHCenter)
                self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
                self.stackedWidget.setStyleSheet("background-color: white;\n"
        "border-radius: 15px;")
                self.stackedWidget.setObjectName("stackedWidget")
                self.SignUpPage = QtWidgets.QWidget()
                self.SignUpPage.setStyleSheet("")
                self.SignUpPage.setObjectName("SignUpPage")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SignUpPage)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.label = QtWidgets.QLabel(self.SignUpPage)
                font = QtGui.QFont()
                font.setFamily("Niagara Solid")
                font.setPointSize(28)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
                self.Message_Widge_on_Sign_Up_Form = QtWidgets.QWidget(self.SignUpPage)
                self.Message_Widge_on_Sign_Up_Form.setMaximumSize(QtCore.QSize(16777215, 0))
                self.Message_Widge_on_Sign_Up_Form.setObjectName("Message_Widge_on_Sign_Up_Form")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Message_Widge_on_Sign_Up_Form)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.Message_Label_on_Sign_up = QtWidgets.QLabel(self.Message_Widge_on_Sign_Up_Form)
                self.Message_Label_on_Sign_up.setStyleSheet("background-color: lightgreen;\n"
        "border-radius: 15px;\n"
        "padding: 15px;")
                self.Message_Label_on_Sign_up.setObjectName("Message_Label_on_Sign_up")
                self.verticalLayout_7.addWidget(self.Message_Label_on_Sign_up)
                self.verticalLayout_2.addWidget(self.Message_Widge_on_Sign_Up_Form)
                spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_2.addItem(spacerItem1)
                self.widget = QtWidgets.QWidget(self.SignUpPage)
                self.widget.setStyleSheet("QLineEdit, QComboBox{\n"
        "    border: 2px solid grey;\n"
        "    border-radius: 15px;\n"
        "    padding: 5px;\n"
        "}")
                self.widget.setObjectName("widget")
                self.gridLayout = QtWidgets.QGridLayout(self.widget)
                self.gridLayout.setObjectName("gridLayout")
                self.label_5 = QtWidgets.QLabel(self.widget)
                self.label_5.setObjectName("label_5")
                self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setObjectName("label_3")
                self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setObjectName("label_2")
                self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setObjectName("label_4")
                self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
                self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
                self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.gridLayout.addWidget(self.lineEdit_4, 5, 1, 1, 1)
                self.label_13 = QtWidgets.QLabel(self.widget)
                self.label_13.setObjectName("label_13")
                self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
                self.lineEdit = QtWidgets.QLineEdit(self.widget)
                self.lineEdit.setObjectName("lineEdit")
                self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
                self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.gridLayout.addWidget(self.lineEdit_3, 5, 0, 1, 1)
                self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_5.setObjectName("lineEdit_5")
                self.gridLayout.addWidget(self.lineEdit_5, 3, 0, 1, 1)
                self.label_6 = QtWidgets.QLabel(self.widget)
                self.label_6.setObjectName("label_6")
                self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
                self.comboBox = QtWidgets.QComboBox(self.widget)
                self.comboBox.setObjectName("comboBox")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
                self.verticalLayout_2.addWidget(self.widget)
                self.widget_2 = QtWidgets.QWidget(self.SignUpPage)
                self.widget_2.setStyleSheet("QPushButton{\n"
        "border-radiius: 15px; padding: 15px; background-color: lightgreen;\n"
        "}")
                self.widget_2.setObjectName("widget_2")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.pushButton = QtWidgets.QPushButton(self.widget_2)
                self.pushButton.setStyleSheet("")
                self.pushButton.setObjectName("pushButton")
                self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
                self.widget_5 = QtWidgets.QWidget(self.widget_2)
                self.widget_5.setObjectName("widget_5")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.pushButton_3 = QtWidgets.QPushButton(self.widget_5)
                self.pushButton_3.setObjectName("pushButton_3")
                self.horizontalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignRight)
                self.verticalLayout_3.addWidget(self.widget_5)
                self.verticalLayout_2.addWidget(self.widget_2)
                spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_2.addItem(spacerItem2)
                self.stackedWidget.addWidget(self.SignUpPage)
                self.LoginForPage = QtWidgets.QWidget()
                self.LoginForPage.setObjectName("LoginForPage")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LoginForPage)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label_7 = QtWidgets.QLabel(self.LoginForPage)
                font = QtGui.QFont()
                font.setFamily("Niagara Solid")
                font.setPointSize(28)
                self.label_7.setFont(font)
                self.label_7.setObjectName("label_7")
                self.verticalLayout_5.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
                self.Message_Widget_On_Login_Form = QtWidgets.QWidget(self.LoginForPage)
                self.Message_Widget_On_Login_Form.setEnabled(True)
                self.Message_Widget_On_Login_Form.setMaximumSize(QtCore.QSize(16777215, 0))
                self.Message_Widget_On_Login_Form.setObjectName("Message_Widget_On_Login_Form")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Message_Widget_On_Login_Form)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.MessageLabel = QtWidgets.QLabel(self.Message_Widget_On_Login_Form)
                self.MessageLabel.setStyleSheet("background-color: lightgreen;\n"
        "border-radius: 15px;\n"
        "padding: 15px;")
                self.MessageLabel.setObjectName("MessageLabel")
                self.verticalLayout_6.addWidget(self.MessageLabel)
                self.verticalLayout_5.addWidget(self.Message_Widget_On_Login_Form)
                spacerItem3 = QtWidgets.QSpacerItem(20, 74, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_5.addItem(spacerItem3)
                self.widget_3 = QtWidgets.QWidget(self.LoginForPage)
                self.widget_3.setStyleSheet("QLineEdit, QComboBox{\n"
        "    border: 2px solid grey;\n"
        "    border-radius: 15px;\n"
        "    padding: 5px;\n"
        "}")
                self.widget_3.setObjectName("widget_3")
                self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
                self.gridLayout_2.setObjectName("gridLayout_2")
                self.label_9 = QtWidgets.QLabel(self.widget_3)
                self.label_9.setObjectName("label_9")
                self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
                self.label_8 = QtWidgets.QLabel(self.widget_3)
                self.label_8.setObjectName("label_8")
                self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
                self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_3)
                self.lineEdit_7.setObjectName("lineEdit_7")
                self.gridLayout_2.addWidget(self.lineEdit_7, 3, 0, 1, 1)
                self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_3)
                self.lineEdit_8.setObjectName("lineEdit_8")
                self.gridLayout_2.addWidget(self.lineEdit_8, 1, 0, 1, 1)
                self.verticalLayout_5.addWidget(self.widget_3)
                self.widget_4 = QtWidgets.QWidget(self.LoginForPage)
                self.widget_4.setStyleSheet("QPushButton{\n"
        "border-radiius: 15px; padding: 15px; background-color: lightgreen;}")
                self.widget_4.setObjectName("widget_4")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
                self.pushButton_2.setStyleSheet("")
                self.pushButton_2.setObjectName("pushButton_2")
                self.verticalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
                self.widget_6 = QtWidgets.QWidget(self.widget_4)
                self.widget_6.setObjectName("widget_6")
                self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.pushButton_6 = QtWidgets.QPushButton(self.widget_6)
                self.pushButton_6.setObjectName("pushButton_6")
                self.verticalLayout_8.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignRight)
                self.verticalLayout_4.addWidget(self.widget_6)
                self.verticalLayout_5.addWidget(self.widget_4)
                spacerItem4 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_5.addItem(spacerItem4)
                self.stackedWidget.addWidget(self.LoginForPage)
                self.verticalLayout.addWidget(self.stackedWidget)
                self.MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi()
                self.stackedWidget.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(self.MainWindow)
        def retranslateUi(self):
                _translate = QtCore.QCoreApplication.translate
                self.centralwidget.setStyleSheet("background-color: lightgrey; border-radius: 15px; ")
                self.MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_12.setText(_translate("MainWindow", "TMS"))
                self.TitleLable.setText(_translate("MainWindow", "Transport Management System"))
                self.label.setText(_translate("MainWindow", "Sign Up Form"))
                self.Message_Label_on_Sign_up.setText(_translate("MainWindow", "Message on Sign Up Form!"))
                self.label_5.setText(_translate("MainWindow", "Confirm Password:"))
                self.label_3.setText(_translate("MainWindow", "Father Name:"))
                self.label_2.setText(_translate("MainWindow", "Name:"))
                self.label_4.setText(_translate("MainWindow", "Password:"))
                self.label_13.setText(_translate("MainWindow", "Username/Email:"))
                self.label_6.setText(_translate("MainWindow", "Status:"))
                self.comboBox.setItemText(0, _translate("MainWindow", "ADMIN"))
                self.comboBox.setItemText(1, _translate("MainWindow", "CLIENT"))
                self.pushButton.setText(_translate("MainWindow", "Register Now!"))
                self.pushButton_3.setText(_translate("MainWindow", "Already have an account?"))
                self.label_7.setText(_translate("MainWindow", "Login Form"))
                self.MessageLabel.setText(_translate("MainWindow", "Message on Login Form!"))
                self.label_9.setText(_translate("MainWindow", "Username/Email:"))
                self.label_8.setText(_translate("MainWindow", "Password:"))
                self.pushButton_2.setText(_translate("MainWindow", "Log In"))
                self.pushButton_6.setText(_translate("MainWindow", "Don\'t have an account?"))
        
        # Functionality For Login Page
        def connect_login_buttons(self):
                self.pushButton_2.clicked.connect(self.Login)
                self.pushButton_6.clicked.connect(self.go_to_signUpPage)
        def go_to_signUpPage(self):
                self.stackedWidget.setCurrentWidget(self.SignUpPage)
        def Login(self):
                Email = self.lineEdit_8.text()
                Password = self.lineEdit_7.text()
                self.cursor.execute("SELECT `fname`, `lname`, `user`, `password`, `confirmpassword`, `status` FROM `admin` WHERE `user` = '{0}' AND `password` = '{1}'".format(Email,Password))
                user_data = self.cursor.fetchone()
                if user_data:
                        self.MessageLabel.setStyleSheet("background-color: lightgreen;\n"
        "border-radius: 15px;\n"
        "padding: 15px;")
                        if user_data[5] == "ADMIN":
                                self.MessageLabel.setText(f"Welcome Back! {user_data[0]}. You are logged in as {user_data[5]}.")
                                self.show_and_hide_message(self.Message_Widget_On_Login_Form)
                                self.MainWindow.hide()
                                os.system("py ./Admin_Dashboard.py")
                        else:
                                self.MessageLabel.setText(f"Welcome Back! {user_data[0]}. You are logged in as {user_data[5]}.")
                                self.show_and_hide_message(self.Message_Widget_On_Login_Form)
                                self.MainWindow.hide()
                                os.system("py ./Client_Dashboard.py")
                else:
                        self.MessageLabel.setStyleSheet("background-color: red;\n"
        "border-radius: 15px;\n"
        "padding: 15px;")
                        self.MessageLabel.setText(f"Invalid Credentials. Please try again!")
                        self.show_and_hide_message(self.Message_Widget_On_Login_Form)
        # Functionality for Sign Up page
        def connect_signup_buttons(self):
                self.pushButton.clicked.connect(self.SignUp)
                self.pushButton_3.clicked.connect(self.go_to_LoginPage)
        def go_to_LoginPage(self):
                self.stackedWidget.setCurrentWidget(self.LoginForPage)
        def SignUp(self):
                # Incomplete
                fname = self.lineEdit.text()
                lname = self.lineEdit_2.text()
                user = self.lineEdit_5.text()
                password = self.lineEdit_3.text()
                c_password = self.lineEdit_4.text()
                status = self.comboBox.currentText()
                if password == c_password:
                        try:
                                self.cursor.execute("INSERT INTO `admin`(`fname`, `lname`, `user`, `password`, `confirmpassword`, `status`) VALUES ('{0}','{1}','{2}','{3}','{4}','{5}')".format(fname,lname,user,password,c_password,status))
                                self.connection.commit()
                                self.Message_Label_on_Sign_up.setStyleSheet("background-color: lightgreen;\n"
                "border-radius: 15px;\n"
                "padding: 15px;")
                                self.Message_Label_on_Sign_up.setText(f"Welcome Aboard, {fname}! You can now login via Email/Username: {user} and password: {password}.")
                                self.show_and_hide_message(self.Message_Widge_on_Sign_Up_Form)
                        except:
                                self.Message_Label_on_Sign_up.setStyleSheet("background-color: red;\n"
                "border-radius: 15px;\n"
                "padding: 15px;")
                                self.Message_Label_on_Sign_up.setText(f"Something went wrong! Check Connection with the server.")
                                self.show_and_hide_message(self.Message_Widge_on_Sign_Up_Form)
                else:
                        self.Message_Label_on_Sign_up.setStyleSheet("background-color: red;\n"
        "border-radius: 15px;\n"
        "padding: 15px;")
                        self.Message_Label_on_Sign_up.setText(f"Both Password and Confirm password doesn't match!")
                        self.show_and_hide_message(self.Message_Widge_on_Sign_Up_Form)

        # UpperButton Connections
        def connect_upper_bar_buttons(self):
                self.pushButton_7.clicked.connect(exit)
                self.pushButton_5.clicked.connect(self.maximizewindow)
        def maximizewindow(self):
                if not self.maximized:
                        self.maximized = True
                        self.animemaximize = QPropertyAnimation(self.MainWindow, b'geometry')
                        self.animemaximize.setDuration(1000)
                        self.animemaximize.setStartValue(QRect(self.MainWindow.x(),self.MainWindow.y(),self.MainWindow.width(),self.MainWindow.height()))
                        self.animemaximize.setEndValue(QRect(0,0,GetSystemMetrics(0),GetSystemMetrics(1)))
                        self.animemaximize.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
                        self.animemaximize.start()
                elif self.maximized:
                        self.maximized = False
                        self.animeshrink = QPropertyAnimation(self.MainWindow, b'geometry')
                        self.animeshrink.setDuration(1000)
                        self.animeshrink.setStartValue(QRect(self.MainWindow.x(),self.MainWindow.y(),self.MainWindow.width(),self.MainWindow.height()))
                        self.animeshrink.setEndValue(QRect(int(GetSystemMetrics(0)/5),int(GetSystemMetrics(1)/7),int(GetSystemMetrics(0)/1.5),int(GetSystemMetrics(1)/1.5)))
                        self.animeshrink.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
                        self.animeshrink.start()
        def show_and_hide_message(self, widget):
                self.anim_1 = QPropertyAnimation(widget, b'maximumHeight')
                self.anim_1.setDuration(1000)
                self.anim_1.setStartValue(0)
                self.anim_1.setEndValue(1000)
                self.anim_1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
                
                self.anim_2 = QPropertyAnimation(widget, b'maximumHeight')
                self.anim_2.setDuration(1000)
                self.anim_2.setStartValue(1000)
                self.anim_2.setEndValue(0)
                self.anim_2.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
                
                t_anim = QSequentialAnimationGroup(self.MainWindow)
                t_anim.addAnimation(self.anim_1)
                t_anim.addAnimation(self.anim_2)
                t_anim.start()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Sign_Up_and_Login_Form("Login")
    sys.exit(app.exec_())